server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: 'create'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

