spring:
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  cloud:
    config:
      override-system-properties: false
---
spring:
  zipkin:
    baseUrl: http://zipkin:9411