
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: megatron
  jpa:
    hibernate:
      ddl-auto: 'create'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

app:
  eureka-server: localhost

---
server:
  port: 8080
spring:
  profiles:
    - docker
app:
  eureka-server: eureka

spring.datasource:
  url: jdbc:mysql://mysql/docker