
server:
  port: 7070

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: megatron
  jpa:
    hibernate:
      ddl-auto: 'create'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

