server:
  port: 8988


app:
  eureka-server: eureka

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---
server:
  port: 8080
spring:
  profiles:
    - docker
app:
  eureka-server: eureka