server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: megatron
  jpa:
    hibernate:
      ddl-auto: 'create'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true

