spring:
  application:
    name: customer
  sleuth:
    sampler:
      probability: 1
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: megatron
  jpa:
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true